### ISSUE TITLE
Use environment variables for confidential data

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/Project_ex01#15]
Checked out https://github.com/ncs-jss/Project_ex01/blob/master/server/config/config.json this file will hold confidential data and shouldn't be committed on github. But if you don't commit the file, everytime you clone the repo you have to create the config.json in appropriate directory. A better way is to use .env file which is not committed. Use [`dotenv`](https://www.npmjs.com/package/dotenv) for this. 

Take a look at https://github.com/dsindia/dsi-portal-server to understand how to use it

**Comment by itaditya** [comment]
why is this closed ?

**Comment by rahul2240** [comment]
@itaditya sir, i used "closes issue" in wrong commit so it is closed but it is now resolved in #20 . Please take a look.
