### ISSUE TITLE
use a persistent session store

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/Project_ex01#26]
From https://www.npmjs.com/package/express-session

>Warning The default server-side session storage, MemoryStore, is purposely not designed for a production environment. It will leak memory under most conditions, does not scale past a single process, and is meant for debugging and developing.

For a list of stores, see [compatible session stores](https://www.npmjs.com/package/express-session#compatible-session-stores).

@rahul2240 I'd suggest use https://www.npmjs.com/package/connect-mongo

**Comment by rahul2240** [comment]
Sir, I am not using sessions now, I am using token.
