### ISSUE TITLE
Date format in datepicker should be dd/mm/yyyyy not mm/dd/yyyy

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/Project_ex01#39]

**Comment by itaditya** [comment]
One thing to boost UX is to fill some details in the start itself. Like you definitely know that the year (even the month) will be the current one. You won't really expect user in 2018 to create event for 2019 and neither will in college (in 90% cases) anyone wants to create one month before. Considering both these things filling the date makes sense. Heck I'd suggest simply fill that day's date as default. Same goes for 'PM' . Most events will start in afternoon. So PM can be filled in default.

If we keep all this filled by default, user only has to change the day. and that is huge win for UX

**Comment by kunalvishnoi** [comment]
Current Date and time is filled by Default

**Comment by itaditya** [comment]
Always mention the issue number in PR, so we can see how you have implemented it.
