### ISSUE TITLE
Directly visiting login page gives 404

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/Project_ex01#44]
Try opening http://eventmanager.surge.sh/login directly by clicking this link, It will give 404 page. That's because surge doesn't have login page route defined and client side routing will kick in only after js has loaded. That's why you get 404 page now but if you have opened login page by clicking on sidebar link ten login page will be opened.

To fix this read - https://surge.sh/help/adding-a-200-page-for-client-side-routing

**Comment by kunalvishnoi** [comment]
Thank you Sir!!
It's Working now.
